# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yanxi.me
tagline:             "personal website on thoughts, stories and ideas."
description:         'A personal website on thoughts, stories and ideas. By <a href="http://yanxi.me/">yanxi</a>'
url:                 http://yanxi.me
baseurl:             ''
paginate:            5
github:
  repo:              https://github.com/yanxi-com/yanxi-com.github.io

# About/contact
author:
  name:              Yan xi
  url:               http://yanxi.me
  email:             yanxi.me@foxmail.com

# Custom vars
version:             1.0.0
