# Permalinks
permalink:           pretty

# Setup
title:               H5nodejs 中前端学习
tagline:             Html5, Nodejs, Javascript, React, Redux, Webpack, ...
url:                 http://h5nodejs.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yanxi
  url:               http://yanxi.me/
  email:             blogbbs@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/yanxi-me/h5nodejs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
