# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yanxi.me
tagline:             "所见･所闻･所思･所感"
description:         '站点导航'
url:                 http://yanxi.me
baseurl:             ''
paginate:            5
github:
  repo:              https://github.com/yanxi-me/yanxi-me.github.io

# About/contact
author:
  name:              Yan xi
  url:               http://yanxi.me
  email:             yanxi.me@foxmail.com

# Custom vars
version:             1.0.0

exclude:             [not_publish]
